[build]
  publish = "."

[build.processing]
  skip_processing = true

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"
